name: Build and Test on Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/get-cmake@v3

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build with CMake
      run: cmake --build build

    - name: Check permissions
      run: |
        icacls build\\bin\\sl.exe /grant Everyone:F
        icacls build\\lib\\sl-ext.dll /grant Everyone:F
        dir build\\bin
        dir build\\lib

    - name: Run checks
      run: |
        build\\bin\\sl.exe quit
      
